services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pfm
      POSTGRES_PASSWORD: pfm
      POSTGRES_DB: pfm_tracking
    ports:
      - "5432:5432"
    volumes:
      - pfm_pg:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # api:
  #   build: ./api
  #   env_file: .env
  #   depends_on: [postgres, redis]
  #   ports: ["3000:3000"]

  # worker:
  #   build: ./worker
  #   env_file: .env
  #   depends_on: [postgres, redis]

  # admin:
  #   build: ./admin
  #   ports: ["5173:5173"]

volumes:
  pfm_pg:
